federation_version: 2
subgraphs:
  locations:
    routing_url: http://localhost:8080/graphql
    schema:
      subgraph_url: http://localhost:8080/graphql
  reviews:
    routing_url: http://localhost:8081/graphql
    schema:
      subgraph_url: http://localhost:8081/graphql